### PR TITLE
Webscraper

### PR DESCRIPTION
**Pull request by Kunal2700**

### CODE REVIEW

**Comment by AAAblaze** [comment]
I am wondering what are those checkpoint ipynb files for and I assume that we don't need those files? Could you please give a short explation on those files? Or unnecessary files could be added in .gitignore file to be avoided adding in the main branch.

**Review by AAAblaze — COMMENTED** [review]
Do we really need some src/.ipynb_checkpoints/xxxxxxx.ipynb files? I am curious about this.

**Comment by Kunal2700** [comment]
I am not sure what they do but they don't have to be added to the repo since we just need the json file

**Comment by ptsheeran** [comment]
> I am not sure what they do but they don't have to be added to the repo since we just need the json file



> I am not sure what they do but they don't have to be added to the repo since we just need the json file

Can you add these files to gitignore and commit again so we can merge this without those files?

**Pull request merged**
